defaults: &defaults
  adapter: postgres
  username: svs

development:
  database: rbus_dev
  <<: *defaults

test: &test
  database: rbus_test
  <<: *defaults
production:
  <<: *defaults
cucumber:
  <<: *test